-
  version: build{build}
  branches:
    only:
    - master
  configuration: Release
  platform: Any CPU
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-final
  before_build:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  build:
    verbosity: minimal
  after_build:
  - cmd: dnu pack src/CoolSms --configuration Release --out "artifacts/CoolSms"
  artifacts:
  - path: '**\*.nupkg'
    name: NuGet
  deploy:
  - provider: NuGet
    api_key:
      secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/

-
  version: build{build}-dev
  branches:
    except:
    - master
  configuration: Debug
  platform: Any CPU
  before_build:
  - cmd: nuget restore
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/
