image: Visual Studio 2017
version: build{build}
skip_branch_with_pr: true
configuration: Release
build_script:
- cmd: 'REM master-build'
- cmd: 'ECHO Configuration: %CONFIGURATION%'
- cmd: 'ECHO Branch: %APPVEYOR_REPO_BRANCH%'
- cmd: 'ECHO HasTag: %APPVEYOR_REPO_TAG%'
- cmd: 'ECHO PR Number: %APPVEYOR_PULL_REQUEST_NUMBER%'
- cmd: 'dotnet restore'
- cmd: 'dotnet build -c %CONFIGURATION%'
test_script:
- cmd: cd test\CoolSms.Tests
- cmd: dotnet test
after_test:
- ps: >-
    if ([string]::IsNullOrEmpty($env:APPVEYOR_REPO_BRANCH)) {
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        dotnet pack -c $env:CONFIGURATION --no-build
      } else 
        dotnet pack -c $env:CONFIGURATION --version-suffix dev$:APPVEYOR_BUILD_NUMBER --no-build
      }
    }
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
  on:
    branch: master
- provider: NuGet
  server: https://www.myget.org/F/bapul/api/v2/package
  api_key:
    secure: X8/Cm8f2M7FVtOuQftWgMlQv8XNMXJ8RbtVkeQkTgoaLb5Bv6Vf5KWcYZSEJ/wIc
  on:
    branch: dev
skip_commits:
  message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/