-
  version: build{build}
  branches:
    only:
    - master
  configuration: Release
  platform: Any CPU
  before_build:
  - cmd: dotnet restore
  - cmd: dotnet build
  build:
    verbosity: minimal
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
  artifacts:
  - path: '**\CoolSms\**\*.nupkg'
    name: NuGet
  deploy:
  - provider: NuGet
    api_key:
      secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/

-
  version: build{build}-dev
  branches:
    except:
    - master
  configuration: Debug
  platform: Any CPU
  before_build:
  - cmd: dotnet restore
  - cmd: dotnet build
  build:
    verbosity: minimal
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/