-
  image: Visual Studio 2017
  version: build{build}
  branches:
    only:
    - master
  skip_branch_with_pr: true
  configuration: Release
  build_script:
  - cmd: dotnet restore
  - cmd: dotnet build -c %CONFIGURATION%
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
  artifacts:
  - path: '**\CoolSms\**\*.nupkg'
    name: NuGet
  before_deploy:
  - cmd: dotnet pack src\CoolSms -c %CONFIGURATION% --no-build
  deploy:
  - provider: NuGet
    api_key:
      secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/

-
  image: Visual Studio 2017
  version: build{build}-ci
  skip_branch_with_pr: true
  configuration: Debug
  build_script:
  - cmd: dotnet restore
  - cmd: dotnet build -c %CONFIGURATION%
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/