version: 1.0.{build}
skip_commits:
  message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    nuget restore

    md artifacts\nuget
build:
  verbosity: minimal
after_build:
- cmd: nuget pack "src\CoolSms\CoolSms.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects -Version %APPVEYOR_BUILD_VERSION% -OutputDirectory "artifacts\nuget"
artifacts:
- path: '**\nuget\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
