-
  image: Visual Studio 2017
  version: build{build}
  branches:
    only:
    - master
  configuration: Release
  platform: Any CPU
  before_build:
  - cmd: dotnet restore
  - cmd: dotnet build -c $(CONFIGURATION)
  - cmd: dotnet pack src\CoolSms -c $(CONFIGURATION)
  build:
    verbosity: minimal
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
  artifacts:
  - path: '**\CoolSms\**\*.nupkg'
    name: NuGet
  deploy:
  - provider: NuGet
    api_key:
      secure: sromj9mN3Uv8dh0Lpb+0/ywpACJM6NPxfCJbBL6AxxWcvxacnAGsvUc68T8ptY2+
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/

-
  image: Visual Studio 2017
  version: build{build}-dev
  branches:
    except:
    - master
  configuration: Debug
  platform: Any CPU
  before_build:
  - cmd: dotnet restore
  - cmd: dotnet build -c $(CONFIGURATION)
  - cmd: dotnet pack src\CoolSms -c $(CONFIGURATION) --version-suffix dev$(BUILD)
  build:
    verbosity: minimal
  test_script:
  - cmd: cd test\CoolSms.Tests
  - cmd: dotnet test
- provider: NuGet
  server: https://www.myget.org/F/bapul/api/v2/package
  api_key:
    secure: X8/Cm8f2M7FVtOuQftWgMlQv8XNMXJ8RbtVkeQkTgoaLb5Bv6Vf5KWcYZSEJ/wIc
  skip_commits:
    message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|Create appveyor.yml/